services:
  - type: web
    name: nurox-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install openai==1.95.0
      pip install -r requirements.txt
    startCommand: "bash start.sh"
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}