services:
  - type: web
    name: nurox-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: OPENAI_API_KEY
        fromEnv: OPENAI_API_KEY
      - key: BOT_TOKEN
        fromEnv: BOT_TOKEN